kind: Service
apiVersion: v1
metadata:
  name: otel
  # namespace: {{ .Values.namespace }}
spec:
  selector:
    name: otel-agent
  ports:
  - name: otlp
    port: 4317
    targetPort: 4317
  - name: http
    port: 4318
    targetPort: 4318